name: Build mt6000

on: 
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: 18 1 * * 2
env:
  CONFIG_FILE: mt6000.config
  CUSTOM_SH: custom.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /opt/microsoft
        sudo rm -rf /opt/pipx
        sudo rm -rf /usr/share/swift
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
        sudo -E apt-get -y autoremove
        sudo -E apt-get autoclean

    - name: Clone source code
      run: |
        git clone -b openwrt-25.12 --single-branch https://github.com/openwrt/openwrt.git openwrt

    - name: Update Install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configuration Customization
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $CUSTOM_SH
        cd openwrt
        $GITHUB_WORKSPACE/$CUSTOM_SH

    - name: Download package
      run: |
        cd openwrt
        make defconfig
        make download

    - name: Build firmware
      run: |
        cd openwrt
        make -j1

    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: mt6000
        path: openwrt/bin
